
services:
  &name ace-step:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: *name
    hostname: *name
    stop_grace_period: 2s
    ports:
      - "7865:7865"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - ACE_OUTPUT_DIR=/app/outputs
    command: python3 acestep/gui.py --server_name 0.0.0.0 --port 7865 --bf16 true --torch_compile true --cpu_offload true --overlapped_decode true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7865/"]
      interval: 60s
      timeout: 10s
      retries: 30
      start_period: 3s
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["compute", "utility", "graphics", "video"]
